# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.18.4

# Mod Properties
mod_version=1.4.2+1.21.1
maven_group=net.dianacraft.lifeskins
archives_base_name=lifeskins

# Dependencies
fabric_version=0.116.8+1.21.1
lifeseries_version=1.4.5+1.21
fabrictailor_version=2.5.0
fcn_version=0.3.3-1.21.1
